image:
  repository: 833453046877.dkr.ecr.us-east-1.amazonaws.com/axiom-ai
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

service:
  type: ClusterIP
  port: 8000

env:
  AI_SERVICE_PORT: "8000"
  KAFKA_ENABLED: "false"

envFrom:
  - secretRef:
      name: axiom-secrets

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuTargetUtilization: 70
