apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axiom-api.fullname" . }}-rds-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axiom-api.labels" . | nindent 4 }}
data:
  global-bundle.pem: |
{{ .Files.Get "files/rds-global-bundle.pem" | indent 4 }}
