apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "axiom-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axiom-ai.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: axiom.saswat.app
    http:
      paths:
      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: {{ include "axiom-ai.fullname" . }}
            port:
              number: {{ .Values.service.port }}
