apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axiom-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "axiom-web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
